insert into Cliente (cod_cliente, dni, nombre, apellidos, telefono, email) values (1, '926383728N', 'Pepe', 'Fanegas Deleto', '959632748', 'pepefan@gmail.com');
insert into Cliente (cod_cliente, dni, nombre, apellidos, telefono, email) values (2, '534109283F', 'Antonio', 'Vicente Cortés', '738028374', 'veceantonio@gmail.com');
INSERT INTO cliente (cod_cliente, dni, nombre, apellidos, telefono, email) VALUES (3, '340398252V', 'Maria', 'Alonso Garcia', '235270276', 'MariaAlonso@gmail.com');
INSERT INTO cliente (cod_cliente, dni, nombre, apellidos, telefono, email) VALUES (4, '127765455H', 'Manolo', 'González Moreno', '807341669', 'ManoloGonzález@gmail.com');
INSERT INTO cliente (cod_cliente, dni, nombre, apellidos, telefono, email) VALUES (5, '111388665G', 'Laura', 'González Alonso', '808882282', 'LauraGonzález@gmail.com');
INSERT INTO cliente (cod_cliente, dni, nombre, apellidos, telefono, email) VALUES (6, '679662474U', 'Manolo', 'Mellado Serna', '426588850', 'ManoloMellado@gmail.com');
INSERT INTO cliente (cod_cliente, dni, nombre, apellidos, telefono, email) VALUES (7, '718421119O', 'Laura', 'Ruiz Romero', '947847215', 'LauraRuiz@gmail.com');
INSERT INTO cliente (cod_cliente, dni, nombre, apellidos, telefono, email) VALUES (8, '217707502R', 'Antonio', 'Rodríguez Moreno', '446882134', 'AntonioRodríguez@gmail.com');
INSERT INTO cliente (cod_cliente, dni, nombre, apellidos, telefono, email) VALUES (9, '394425518J', 'Roberto', 'Cortés Serna', '258723606', 'RobertoCortés@gmail.com');
INSERT INTO cliente (cod_cliente, dni, nombre, apellidos, telefono, email) VALUES (10, '583821944P', 'Marta', 'Romero Cortés', '565076602', 'MartaRomero@gmail.com');
INSERT INTO cliente (cod_cliente, dni, nombre, apellidos, telefono, email) VALUES (11, '215809628W', 'Francisco', 'Serna Garcia', '591386191', 'FranciscoSerna@gmail.com');
INSERT INTO cliente (cod_cliente, dni, nombre, apellidos, telefono, email) VALUES (12, '572358060Z', 'Francisco', 'González Serna', '587988393', 'FranciscoGonzález@gmail.com');
INSERT INTO cliente (cod_cliente, dni, nombre, apellidos, telefono, email) VALUES (13, '118537052M', 'Manolo', 'Romero Mellado', '944352374', 'ManoloRomero@gmail.com');
INSERT INTO cliente (cod_cliente, dni, nombre, apellidos, telefono, email) VALUES (14, '180741506W', 'Marta', 'Moreno González', '169603000', 'MartaMoreno@gmail.com');
INSERT INTO cliente (cod_cliente, dni, nombre, apellidos, telefono, email) VALUES (15, '534444417K', 'Manolo', 'Mellado Cortés', '179094482', 'ManoloMellado@gmail.com');
INSERT INTO cliente (cod_cliente, dni, nombre, apellidos, telefono, email) VALUES (16, '264948582H', 'Francisco', 'Rodríguez Romero', '515272373', 'FranciscoRodríguez@gmail.com');
INSERT INTO cliente (cod_cliente, dni, nombre, apellidos, telefono, email) VALUES (17, '239583734T', 'Vicente', 'Alonso Rodríguez', '184458487', 'VicenteAlonso@gmail.com');
INSERT INTO cliente (cod_cliente, dni, nombre, apellidos, telefono, email) VALUES (18, '195373500Y', 'Roberto', 'Romero Alonso', '668332813', 'RobertoRomero@gmail.com');
INSERT INTO cliente (cod_cliente, dni, nombre, apellidos, telefono, email) VALUES (19, '322678164Z', 'Crristian', 'Moreno Garcia', '223045701', 'CrristianMoreno@gmail.com');
INSERT INTO cliente (cod_cliente, dni, nombre, apellidos, telefono, email) VALUES (20, '914272153U', 'Francisco', 'González Rodríguez', '444724233', 'FranciscoGonzález@gmail.com');
INSERT INTO cliente (cod_cliente, dni, nombre, apellidos, telefono, email) VALUES (21, '703793454H', 'Laura', 'Rodríguez Mellado', '733562810', 'LauraRodríguez@gmail.com');
INSERT INTO cliente (cod_cliente, dni, nombre, apellidos, telefono, email) VALUES (22, '707032918V', 'Roberto', 'Romero González', '341313905', 'RobertoRomero@gmail.com');
INSERT INTO cliente (cod_cliente, dni, nombre, apellidos, telefono, email) VALUES (23, '141503268I', 'Laura', 'Ruiz Moreno', '243404868', 'LauraRuiz@gmail.com');
INSERT INTO cliente (cod_cliente, dni, nombre, apellidos, telefono, email) VALUES (24, '712111995V', 'Antonio', 'Serna Cortés', '270504360', 'AntonioSerna@gmail.com');
INSERT INTO cliente (cod_cliente, dni, nombre, apellidos, telefono, email) VALUES (25, '612953967E', 'Crristian', 'Alonso González', '573120249', 'CrristianAlonso@gmail.com');
INSERT INTO cliente (cod_cliente, dni, nombre, apellidos, telefono, email) VALUES (26, '621041388E', 'Vicente', 'González Mellado', '525126842', 'VicenteGonzález@gmail.com');
INSERT INTO cliente (cod_cliente, dni, nombre, apellidos, telefono, email) VALUES (27, '705141516K', 'Antonio', 'Romero Ruiz', '119002248', 'AntonioRomero@gmail.com');
INSERT INTO cliente (cod_cliente, dni, nombre, apellidos, telefono, email) VALUES (28, '552577069B', 'Antonio', 'González Garcia', '950136795', 'AntonioGonzález@gmail.com');
INSERT INTO cliente (cod_cliente, dni, nombre, apellidos, telefono, email) VALUES (29, '725586207B', 'Marta', 'González Mellado', '196706755', 'MartaGonzález@gmail.com');
INSERT INTO cliente (cod_cliente, dni, nombre, apellidos, telefono, email) VALUES (30, '834037757N', 'Marta', 'González Alonso', '766251291', 'MartaGonzález@gmail.com');
INSERT INTO cliente (cod_cliente, dni, nombre, apellidos, telefono, email) VALUES (31, '210251715I', 'Vicente', 'Romero Mellado', '512009323', 'VicenteRomero@gmail.com');
INSERT INTO cliente (cod_cliente, dni, nombre, apellidos, telefono, email) VALUES (32, '305278741T', 'Laura', 'Serna Ruiz', '732511479', 'LauraSerna@gmail.com');

insert into Trabajador (id_trabajador, fecha_nacimiento, dni, nombre, apellidos, foto_trabajador, is_admin) values (1, '1999-02-03', '819473842M', 'Trevor', 'Santo Triste', 'https://robohash.org/129837', false);
insert into Trabajador (id_trabajador, fecha_nacimiento, dni, nombre, apellidos, foto_trabajador, is_admin) values (12, '1983-12-23', '837291048S', 'Vicente', 'Del Bosque', 'https://robohash.org/323487', false);
INSERT INTO trabajador (id_trabajador, fecha_nacimiento, dni, nombre, apellidos, foto_trabajador) values (2, ' 1996-3-1', '827226922Y', 'Vicente', 'Moreno Mellado', 'http://robohash.org/VicenteMoreno/');
INSERT INTO trabajador (id_trabajador, fecha_nacimiento, dni, nombre, apellidos, foto_trabajador) values (3, ' 1997-7-12', '482040112G', 'Manolo', 'Moreno Serna', 'http://robohash.org/ManoloMoreno/');
INSERT INTO trabajador (id_trabajador, fecha_nacimiento, dni, nombre, apellidos, foto_trabajador) values (4, ' 2000-9-27', '893969818X', 'Crristian', 'Rodríguez Cortés', 'http://robohash.org/CrristianRodríguez/');
INSERT INTO trabajador (id_trabajador, fecha_nacimiento, dni, nombre, apellidos, foto_trabajador) values (5, ' 1996-6-4', '733901144R', 'Roberto', 'González Garcia', 'http://robohash.org/RobertoGonzález/');
INSERT INTO trabajador (id_trabajador, fecha_nacimiento, dni, nombre, apellidos, foto_trabajador) values (6, ' 1983-8-21', '971730306C', 'Crristian', 'Ruiz González', 'http://robohash.org/CrristianRuiz/');
INSERT INTO trabajador (id_trabajador, fecha_nacimiento, dni, nombre, apellidos, foto_trabajador) values (7, ' 1983-5-25', '196576925F', 'Francisco', 'Ruiz Alonso', 'http://robohash.org/FranciscoRuiz/');
INSERT INTO trabajador (id_trabajador, fecha_nacimiento, dni, nombre, apellidos, foto_trabajador) values (8, ' 1997-3-7', '811484689V', 'Maria', 'Garcia Cortés', 'http://robohash.org/MariaGarcia/');
INSERT INTO trabajador (id_trabajador, fecha_nacimiento, dni, nombre, apellidos, foto_trabajador) values (9, ' 1995-9-22', '936617545F', 'Crristian', 'Ruiz Garcia', 'http://robohash.org/CrristianRuiz/');
INSERT INTO trabajador (id_trabajador, fecha_nacimiento, dni, nombre, apellidos, foto_trabajador) values (10, ' 1998-9-24', '174937138K', 'Francisco', 'Moreno Alonso', 'http://robohash.org/FranciscoMoreno/');
INSERT INTO trabajador (id_trabajador, fecha_nacimiento, dni, nombre, apellidos, foto_trabajador) values (11, ' 1995-5-13', '875085696P', 'Francisco', 'Mellado González', 'http://robohash.org/FranciscoMellado/');

insert into Vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) values ('2938GAK', 'AUTOBUS', 'kjas82dskj3', 'Audi', 'A3');
insert into Vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) values ('7482LWJ', 'TURISMO', 'yqiebc82nd1', 'BMW', 'serie X');
INSERT INTO vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) VALUES ('2537JFV', 'TURISMO', 'R9IVXWXNFV7UQJG88', 'peugeot', 'hatchback');
INSERT INTO vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) VALUES ('6786FMG', 'FURGONETA', 'RJENJYCLEII8W9LRM', 'lexus', 'hatchback');
INSERT INTO vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) VALUES ('1472QIJ', 'TURISMO', 'J9B2HKBMG1XIHZE52', 'toyota', '76v');
INSERT INTO vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) VALUES ('3728COM', 'FURGONETA', 'M73CPODYKYV8YE4LN', 'BMW', 'mini');
INSERT INTO vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) VALUES ('4951OND', 'TURISMO', 'LB66SVIR91PY19CP6', 'volkswagen', 'hatchback');
INSERT INTO vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) VALUES ('2587KXY', 'AUTOBUS', 'Z910PNOM2YRBJ27658', 'lexus', 'snippet');
INSERT INTO vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) VALUES ('3302RHC', 'COMPACTO', 'ZWZS8BVQ2XJS2Z10OX', 'volkswagen', 'pn23');
INSERT INTO vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) VALUES ('1301BNN', 'FURGONETA', 'QDL19QDECXX7ZSIXR', 'Hyundai', 'pn23');
INSERT INTO vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) VALUES ('2805RPV', 'TURISMO', 'V831QVXCQCZRNK8JR', 'Hyundai', 'hatchback');
INSERT INTO vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) VALUES ('6862KGO', 'FURGONETA', 'WI236IYWJSJ189K1I', 'toyota', '76v');
INSERT INTO vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) VALUES ('6767XCU', 'TURISMO', 'J5LY5EWQ8X9PT4T1T', 'volkswagen', '76v');
INSERT INTO vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) VALUES ('1411QBE', 'COMPACTO', 'N5WNY9H6SKZHMB5KT', 'peugeot', 'coupe');
INSERT INTO vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) VALUES ('2726TBD', 'AUTOBUS', 'C1652B3U96IRQO6US', 'lexus', 'xsara');
INSERT INTO vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) VALUES ('7738XMW', 'COMPACTO', '1ZN8R1E626Y15381N', 'lexus', 'golf');
INSERT INTO vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) VALUES ('6433QTN', 'AUTOBUS', 'WJVTJG7106BZYSHFZO', 'Citroen', 'mini');
INSERT INTO vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) VALUES ('241RJB', 'TURISMO', 'FZ5PY96TUWVWNHH910', 'peugeot', 'snippet');
INSERT INTO vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) VALUES ('1464LWD', 'TURISMO', '35NM6LERFL8RZ1TRJ', 'BMW', 'xsara');
INSERT INTO vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) VALUES ('7042GPM', 'AUTOBUS', 'C9H4HR9QDBR9CXF5F', 'toyota', 'golf');
INSERT INTO vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) VALUES ('7941QLN', 'TURISMO', '8V10877MYW8WQ58BJZ', 'BMW', 'golf');
INSERT INTO vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) VALUES ('6472SSZ', 'COMPACTO', 'Q5JR39W3X8E7GX10BP', 'peugeot', 'i30');
INSERT INTO vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) VALUES ('8450YFY', 'TURISMO', 'RSM1OTVYHW665PJ4X', 'toyota', 'snippet');
INSERT INTO vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) VALUES ('5053KNL', 'AUTOBUS', 'LOY10JJFHIN3DPMGVS', 'Hyundai', 'xsara');
INSERT INTO vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) VALUES ('5283OXY', 'COMPACTO', 'W8CDV91LVPLCS9JBY', 'Citroen', 'snippet');
INSERT INTO vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) VALUES ('2792SIY', 'COMPACTO', 'QV4K1RGBM9N1J10XU5', 'lexus', 'XV1');
INSERT INTO vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) VALUES ('2134JDB', 'TURISMO', 'DZKK6GB9OMTYQKLIB', 'peugeot', 'a20x');
INSERT INTO vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) VALUES ('8668IYK', 'FURGONETA', 'Z10HGJ55ZDP1K2510TB', 'volkswagen', 'mini');
INSERT INTO vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) VALUES ('713ISM', 'COMPACTO', '9KSIKGJ2UI10EGUI10P', 'peugeot', 'hatchback');
INSERT INTO vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) VALUES ('5927SBD', 'COMPACTO', 'V10OF4XX57EFDRWI3P', 'Hyundai', 'xsara');
INSERT INTO vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) VALUES ('3945YZV', 'FURGONETA', '4PZ839SUQSBY710810B', 'Hyundai', 'hatchback');
INSERT INTO vehiculo (matricula, tipo_vehiculo, bastidor, marca, modelo) VALUES ('8223TTF', 'COMPACTO', 'B6ZSH3DTLKXUTX2IZ', 'Hyundai', 'mini');


insert into proveedor (id_proveedor, nombre, direccion, descripcion) values (1, 'Lodrones', 'C/laundra 23', 'distribuidor de trocolas');
INSERT INTO proveedor (id_proveedor, nombre, direccion, descripcion) VALUES (2, 'SpeedTech', 'C/Hawthorn Drive nº 37', 'Especialistas en productos de rendimiento para automóviles.');
INSERT INTO proveedor (id_proveedor, nombre, direccion, descripcion) VALUES (3, 'AutoPartsPlus', 'C/Hawthorn Drive nº 22', 'Proveedores de sistemas de suspensión de alto rendimiento.');
INSERT INTO proveedor (id_proveedor, nombre, direccion, descripcion) VALUES (4, 'RaceGear', 'C/Beech Avenue nº 59', 'Suministro de combustible de alto octanaje para competición.');
INSERT INTO proveedor (id_proveedor, nombre, direccion, descripcion) VALUES (5, 'MotorSportSupplies', 'C/Ash Street nº 92', 'Ofrecemos soluciones de motores y sistemas de diagnóstico.');
INSERT INTO proveedor (id_proveedor, nombre, direccion, descripcion) VALUES (6, 'TurboTech', 'C/Ash Street nº 17', 'Suministro de combustible de alto octanaje para competición.');
INSERT INTO proveedor (id_proveedor, nombre, direccion, descripcion) VALUES (7, 'PerformanceWheels', 'C/Maple Avenue nº 74', 'Ofrecemos equipamiento para pilotos y entusiastas del automovilismo.');
INSERT INTO proveedor (id_proveedor, nombre, direccion, descripcion) VALUES (8, 'TrackTires', 'C/Ash Street nº 43', 'Ofrecemos soluciones de motores y sistemas de diagnóstico.');
INSERT INTO proveedor (id_proveedor, nombre, direccion, descripcion) VALUES (9, 'ExhaustMasters', 'C/Maple Avenue nº 49', 'Expertos en sistemas de turboalimentación de alto rendimiento.');
INSERT INTO proveedor (id_proveedor, nombre, direccion, descripcion) VALUES (10, 'CarbonFiberTech', 'C/Alder Court nº 35', 'Especialistas en aceites y lubricantes para automóviles.');
INSERT INTO proveedor (id_proveedor, nombre, direccion, descripcion) VALUES (11, 'RacingBrakeSystems', 'C/Juniper Lane nº 51', 'Especialistas en aceites y lubricantes para automóviles.');

insert into producto (referencia, proveedor_id_proveedor, nombre, precio, pvp, descripcion) values ('kj23jsd', 1, 'junta la trocola', 12.3, 15, 'una perfercamente normal junta la trocola');

ALTER SEQUENCE hibernate_sequence RESTART WITH 1000;